### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by beteland123** [beteland123/recipe_app#29]
In this issue, I share with you:

Link to the repo:
https://github.com/beteland123/recipe_app

https://github.com/users/beteland123/projects/5

I have not been assigned a partner for pair programming,  This is my collaboration information 

![colb_info](https://github.com/beteland123/recipe_app/assets/91183694/d3012261-1c33-423a-9a71-c774c519835e)

 One Group team member: @beteland123

**Comment by divinecharlotte** [comment]
# Hello @beteland123   😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say other than... it's time to merge it 👍🏻 ✅ 
### To Highlight 💯

- Good implementation of the project requirements ✔️
- Descriptive issue✔️






## Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
